apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 590184081927.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:c85db67fafcd905b1fe925dd0f2eb0d203893699
        ports:
        - containerPort: 80
