apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 590184081927.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:c85db67fafcd905b1fe925dd0f2eb0d203893699
        ports:
        - containerPort: 80
