apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 997334016513.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:9c82f469131339181c8eeb9073b472e4bff1dc6c
        ports:
        - containerPort: 80
