apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 621120073967.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:86585711f1f1bcde9794e3f9e6641d90f5738875
        ports:
        - containerPort: 80
