apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 621120073967.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:6537334c151589cb4bf618de7eccec753a33bdcc
        ports:
        - containerPort: 80
