apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:           # This is the Deployment spec
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:     # FIXED: Now indented 2 spaces under spec
    metadata:
      labels:
        app: googlegrocery
    spec:       # This is the Pod spec (indented under template)
      containers:
      - name: googlegrocery
        image: 621120073967.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:f1714f980f197261f8f0225791cae596fef6a785
        ports:
        - containerPort: 80
