apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:           # This is the Deployment spec
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:     # FIXED: Now indented 2 spaces under spec
    metadata:
      labels:
        app: googlegrocery
    spec:       # This is the Pod spec (indented under template)
      containers:
      - name: googlegrocery
        image: 997334016513.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:6cb8dba691c449e393ac44ed86ed5e4139b958b5
        ports:
        - containerPort: 80
